import { Achievement } from "@/types/content";

/**
 * ACHIEVEMENTS
 *
 * Recognition and results tied to the work in projects.ts / experiences.ts.
 * Keep these short — the full story lives on the linked project/experience.
 * This is the "what happened and why it matters" layer, not a re-telling.
 */
export const achievements: Achievement[] = [
  {
    id: "ach-02",
    slug: "bits-yeb",
    title: "1st Runner-Up — BITS Pilani Young Entrepreneurship Bootcamp",
    issuer: "BITS Pilani",
    year: 2024,
    category: "competition",
    tier: "featured",
    summary: "Finished as 1st Runner-Up in the entrepreneurship competition.",
    context: "Entrepreneurship bootcamp at the BITS Pilani campus.",
    whyItMatters: "One of my strongest entrepreneurship results.",
    relatedExperiences: ["exp-hack-01"],
  },
  {
    id: "ach-01",
    slug: "innoventure-national-final",
    title: "InnoVenture Grand National Finale — 2023 & 2024",
    issuer: "InnoVenture",
    year: 2024,
    dateLabel: "2023 & 2024",
    category: "competition",
    tier: "featured",
    summary: "Reached the Grand National Finale in two consecutive years.",
    context: "Entrepreneurship and innovation competition involving multiple rounds.",
    whyItMatters: "Demonstrates sustained interest in entrepreneurship, innovation and solving real-world problems.",
    relatedExperiences: ["exp-hack-01"],
  },
  {
    id: "ach-03",
    slug: "masters-union-ai-final",
    title: "Master's Union AI Hackathon — Final Round",
    issuer: "Master's Union",
    year: 2025,
    category: "competition",
    tier: "significant",
    summary: "Qualified for the final round of an AI-focused innovation and problem-solving competition.",
    context: "Presented the project in the final round.",
    whyItMatters: "Reflects my interest in applying AI to practical problems.",
    relatedProjects: ["proj-01"],
    relatedExperiences: ["exp-hack-01"],
    relatedSkills: ["skill-product"],
  },
  {
    id: "ach-04",
    slug: "masters-union-startup-final",
    title: "Master's Union High School Startup League — Final Round",
    issuer: "Master's Union",
    year: 2026,
    category: "competition",
    tier: "significant",
    summary: "Qualified for the final round of a national startup competition.",
    context: "Presented the project at the Gurgaon campus.",
    whyItMatters: "Shows continued involvement in entrepreneurship beyond a single competition.",
    relatedProjects: ["proj-02"],
    relatedExperiences: ["exp-hack-01"],
  },
  {
    id: "ach-05",
    slug: "theatre-first",
    title: "1st Place — Shistech Inter-School Theatre Competition",
    issuer: "Shistech",
    year: 2026,
    category: "award",
    tier: "significant",
    summary: "Won first place in an inter-school theatre competition.",
    context: "Inter-school theatre and performance competition.",
    whyItMatters: "One of my strongest cultural and performing-arts achievements.",
    relatedExperiences: ["exp-theatre-01"],
    relatedSkills: ["skill-communication"],
  },
  {
    id: "ach-06",
    slug: "world-scholars-cup",
    title: "World Scholar's Cup — Gold & Silver Medals",
    issuer: "World Scholar's Cup",
    year: 2025,
    category: "academic",
    tier: "significant",
    summary: "Qualified for Round 2 and earned Gold and Silver Medals.",
    context: "International competition involving debate, writing and team challenges.",
    whyItMatters: "Demonstrates communication, collaboration and intellectual curiosity.",
    relatedSkills: ["skill-communication"],
  },
  {
    id: "ach-07",
    slug: "camp-yellow",
    title: "Bronze Medal — Camp Yellow International Mathematics Competition",
    issuer: "Camp Yellow",
    year: 2024,
    category: "academic",
    tier: "archive",
    summary: "Won a Bronze Medal in the Final Round.",
    context: "International mathematics competition.",
    whyItMatters: "Reflects strength and sustained interest in mathematical problem solving.",
    relatedSkills: ["skill-systems-thinking"],
  },
  {
    id: "ach-08",
    slug: "janak-equestrian",
    title: "4 Gold Medals — Janak Equestrian Competition",
    issuer: "Janak",
    year: 2025,
    category: "award",
    tier: "archive",
    summary: "Won four Gold Medals in competitive equestrian events.",
    context: "Competitive equestrian tournament.",
    whyItMatters: "Represents a long-standing commitment to horse riding.",
    relatedExperiences: ["exp-school-12"],
  },
  {
    id: "ach-09",
    slug: "inter-school-equestrian",
    title: "3 Medals — Inter-School Equestrian Show",
    issuer: "Inter-School Equestrian Show",
    year: 2024,
    category: "award",
    tier: "archive",
    summary: "Won three medals and received certificates.",
    context: "School-representative equestrian competition.",
    whyItMatters: "Shows consistency in competitive sport.",
    relatedExperiences: ["exp-school-12"],
  },
  {
    id: "ach-10",
    slug: "acer",
    title: "ACER Academic Recognition",
    issuer: "ACER",
    year: 2024,
    dateLabel: "2022 — 2024",
    category: "academic",
    tier: "archive",
    summary: "Received medals and academic recognition across 2022, 2023 and 2024 assessments, including high distinction.",
    context: "Internationally benchmarked academic assessments in English, Mathematics and Science.",
    whyItMatters: "Provides evidence of academic consistency alongside my extracurricular work.",
  },
];
