import { Experience } from "@/types/content";

/**
 * WHAT I DO
 *
 * Things that shaped you but aren't "projects" — leadership roles,
 * competitions, speaking, theatre, volunteering, school life, etc.
 * Same tier system as projects: featured / significant / archive.
 */
export const experiences: Experience[] = [
  {
    id: "exp-lead-01",
    slug: "flair-fest-core",
    title: "Flair Fest Core Team",
    organization: "Jayshree Periwal International School",
    year: 2026,
    category: "leadership",
    tier: "featured",
    themes: ["leading"],
    summary: "Helped organise and execute the full school cultural event as part of the Core Team.",
    description:
      "A hands-on event leadership experience involving planning, coordination and execution of a large school cultural event.",
    role: "Core Team",
    highlights: [
      "Helped organise and execute the full event.",
      "Worked collaboratively across different event requirements and responsibilities.",
      "Contributed to making the event run successfully from planning through execution.",
    ],
    relatedSkills: ["skill-leadership", "skill-communication"],
  },
  {
    id: "exp-hack-01",
    slug: "innovation-competitions",
    title: "Entrepreneurship & Innovation Competitions",
    organization: "Multiple organisations",
    year: 2026,
    dateLabel: "2023 — 2026",
    category: "competition",
    tier: "featured",
    themes: ["competing", "building"],
    summary: "Repeated involvement in entrepreneurship, startup and AI competitions.",
    description:
      "Participated in competitions that required developing ideas, presenting solutions, collaborating and responding to feedback.",
    role: "Participant / Project Creator",
    highlights: [
      "Reached the Grand National Finale of InnoVenture in both 2023 and 2024.",
      "1st Runner-Up at the BITS Pilani Young Entrepreneurship Bootcamp.",
      "Reached the final round of the Master's Union AI Hackathon and High School Startup League.",
    ],
    relatedSkills: ["skill-product", "skill-systems-thinking"],
    relatedProjects: ["proj-01", "proj-02"],
    relatedAchievements: ["ach-01", "ach-02", "ach-03", "ach-04"],
  },
  {
    id: "exp-theatre-01",
    slug: "tas-productions",
    title: "TAS Productions — Acting",
    organization: "TAS Productions",
    year: 2026,
    category: "theatre",
    tier: "significant",
    themes: ["creating"],
    summary: "Participated as an actor in a school theatre production.",
    description:
      "A performing-arts experience focused on acting, rehearsal and working as part of a production team.",
    role: "Actor",
    relatedSkills: ["skill-communication"],
    relatedAchievements: ["ach-05"],
  },
  {
    id: "exp-vol-01",
    slug: "boiler-room",
    title: "Boiler Room Volunteer",
    organization: "Jayshree Periwal International School",
    year: 2026,
    category: "volunteering",
    tier: "significant",
    themes: ["leading"],
    summary: "Volunteered in support of a school event.",
    description: "Supported the event as a student volunteer and contributed to its execution.",
    relatedSkills: ["skill-leadership"],
  },
  {
    id: "exp-school-02",
    slug: "pbl-emcee",
    title: "PBL Emcee & Crew",
    year: 2025,
    dateLabel: "2022 — 2025",
    category: "school",
    tier: "significant",
    themes: ["leading", "creating"],
    summary: "Contributed to PBL events through emceeing, media, auditions and event support.",
    role: "Emcee / Crew; handled the main scoresheet and announcements.",
    relatedSkills: ["skill-communication"],
  },
  {
    id: "exp-school-03",
    slug: "youth-ambassador",
    title: "Youth Ambassador Program",
    year: 2024,
    category: "leadership",
    tier: "significant",
    themes: ["leading"],
    summary: "Participated in a student leadership and ambassador programme.",
    role: "Youth Ambassador",
    relatedSkills: ["skill-leadership"],
  },
  {
    id: "exp-school-12",
    slug: "equestrian",
    title: "Equestrian Competition",
    year: 2026,
    dateLabel: "Multiple years",
    category: "sport",
    tier: "significant",
    themes: ["competing"],
    summary: "Represented my school in equestrian competitions and continued competing across school and external events.",
    role: "Equestrian competitor",
    relatedAchievements: ["ach-08", "ach-09"],
  },
  {
    id: "exp-speak-01",
    slug: "public-speaking",
    title: "Public Speaking Workshop",
    organization: "School Public Speaking Workshop",
    year: 2025,
    category: "speaking",
    tier: "archive",
    themes: ["leading", "exploring"],
    summary: "Facilitated a public-speaking workshop for other students.",
    description: "Shared public-speaking knowledge and helped other students develop confidence and communication skills.",
    relatedSkills: ["skill-communication"],
  },
  {
    id: "exp-media-01",
    slug: "school-news",
    title: "MYP News Desk Reporter",
    year: 2024,
    category: "media",
    tier: "archive",
    themes: ["creating"],
    summary: "Worked as a student reporter for the school's MYP News Desk.",
    relatedSkills: ["skill-writing"],
  },
  {
    id: "exp-workshop-01",
    slug: "inspireability-speaking",
    title: "Inspireability Speaking Mentor",
    year: 2025,
    category: "speaking",
    tier: "archive",
    themes: ["leading"],
    summary: "Mentored participants in a public-speaking event.",
    relatedSkills: ["skill-communication"],
  },
  {
    id: "exp-school-01",
    slug: "round-square",
    title: "Round Square Zoom Postcard Session",
    year: 2024,
    category: "conference",
    tier: "archive",
    themes: ["exploring"],
    summary: "Served as an emcee for an international student engagement and cultural exchange event.",
    relatedSkills: ["skill-communication"],
  },
  {
    id: "exp-school-04",
    slug: "inspireability-design-tech",
    title: "Inspireability Design & Tech Team",
    year: 2025,
    category: "other",
    tier: "archive",
    themes: ["creating"],
    summary: "Contributed to event design and technology, including creating brochures.",
    role: "Design & Technology Team",
    relatedSkills: ["skill-design"],
  },
  {
    id: "exp-school-05",
    slug: "round-square-symposium",
    title: "Round Square Symposium",
    year: 2024,
    category: "conference",
    tier: "archive",
    themes: ["exploring"],
    summary: "Attended and supported an international student-focused event.",
    role: "Participant / Volunteer / Buddy",
    relatedSkills: ["skill-communication"],
  },
  {
    id: "exp-school-06",
    slug: "mini-mun",
    title: "Mini MUN 5.0",
    year: 2023,
    category: "conference",
    tier: "archive",
    themes: ["exploring"],
    summary: "Participated in a Model United Nations experience focused on discussion and diplomacy.",
    role: "Participant",
    relatedSkills: ["skill-communication"],
  },
  {
    id: "exp-school-07",
    slug: "thailand-exchange",
    title: "Thailand Culture Exchange Program",
    year: 2023,
    category: "community",
    tier: "archive",
    themes: ["exploring"],
    summary: "Participated as a buddy supporting cultural exchange.",
    role: "Buddy",
  },
  {
    id: "exp-school-08",
    slug: "digital-horizons",
    title: "Global Youth Action Fund — Digital Horizons",
    year: 2025,
    category: "community",
    tier: "archive",
    themes: ["leading", "exploring"],
    summary: "Contributed to a social-impact education initiative focused on improving access to education through technology.",
    role: "Project participant; submitted a pitch and proposal to the IB board.",
    relatedSkills: ["skill-systems-thinking"],
    relatedProjects: ["proj-02"],
  },
  {
    id: "exp-school-09",
    slug: "breaking-in-bhaskara",
    title: "Breaking in Bhaskara — Cyber Security Podcast",
    year: 2025,
    category: "media",
    tier: "archive",
    themes: ["creating"],
    summary: "Contributed as a speaker to a student-produced cybersecurity podcast.",
    role: "Speaker",
    relatedSkills: ["skill-communication"],
  },
  {
    id: "exp-school-10",
    slug: "cultural-fest",
    title: "Cultural Fest",
    year: 2024,
    category: "school",
    tier: "archive",
    themes: ["creating"],
    summary: "Participated in a school cultural event.",
    role: "Participant",
  },
  {
    id: "exp-school-11",
    slug: "global-university-fair",
    title: "PWS Global University Fair",
    year: 2025,
    category: "school",
    tier: "archive",
    themes: ["exploring"],
    summary: "Participated in a large school-wide university and community event.",
    role: "Participant",
  },
  {
    id: "exp-school-13",
    slug: "junior-make-a-thon",
    title: "Junior-Make-A-Thon",
    year: 2023,
    category: "competition",
    tier: "archive",
    themes: ["building", "competing"],
    summary: "Participated in an innovation and rapid-prototyping competition involving collaborative challenges.",
    relatedSkills: ["skill-systems-thinking"],
  },
  {
    id: "exp-school-14",
    slug: "design-thinking-toi-samsung",
    title: "Design Thinking Workshop by TOI & Samsung",
    year: 2023,
    category: "workshop",
    tier: "archive",
    themes: ["exploring", "creating"],
    summary: "Completed a design-thinking and innovation workshop involving activities and projects, and received a certificate.",
    relatedSkills: ["skill-design"],
  },
  {
    id: "exp-school-15",
    slug: "ai-intensive-google-kaggle",
    title: "5-Day AI Intensive Course by Google & Kaggle",
    year: 2025,
    category: "workshop",
    tier: "archive",
    themes: ["exploring"],
    summary: "Successfully completed an intensive programme focused on artificial intelligence and machine learning.",
    relatedSkills: ["skill-product"],
    relatedProjects: ["proj-01"],
  },
  {
    id: "exp-school-16",
    slug: "pathways-got-talent",
    title: "Emcee at Pathways Got Talent",
    year: 2024,
    category: "school",
    tier: "archive",
    themes: ["leading", "creating"],
    summary: "Served as the official emcee for a school-wide talent showcase, hosting and presenting the event.",
    relatedSkills: ["skill-communication"],
  },
  {
    id: "exp-school-17",
    slug: "aiyyo-essay-writing",
    title: "Aiyyo Essay Writing Competition",
    year: 2023,
    category: "competition",
    tier: "archive",
    themes: ["creating"],
    summary: "Participated in a philosophical and analytical writing competition focused on developing written expression and analysis.",
    relatedSkills: ["skill-writing"],
  },
  {
    id: "exp-school-18",
    slug: "reading-programme",
    title: "Reading Programme / Shelf Indulgence Program",
    year: 2023,
    dateLabel: "2022 & 2023",
    category: "school",
    tier: "archive",
    themes: ["exploring"],
    summary: "Actively completed the reading and literary-enrichment programme across both years.",
    relatedSkills: ["skill-writing"],
  },
  {
    id: "exp-school-19",
    slug: "indiana-university-finance-workshop",
    title: "International Finance and Development Workshop by Indiana University",
    year: 2025,
    category: "workshop",
    tier: "archive",
    themes: ["exploring"],
    summary: "Successfully completed an academic workshop focused on economics, finance and development.",
    relatedSkills: ["skill-systems-thinking"],
  },
  {
    id: "exp-school-20",
    slug: "harmony-equestrian",
    title: "Harmony Equestrian Show",
    year: 2024,
    category: "sport",
    tier: "archive",
    themes: ["competing"],
    summary: "Participated in a prestigious equestrian competition and showcase.",
  },
  {
    id: "exp-school-21",
    slug: "inter-house-horse-riding",
    title: "Inter-House Horse Riding Competitions",
    year: 2023,
    category: "sport",
    tier: "archive",
    themes: ["competing"],
    summary: "Participated in school-level equestrian competitions, achieving 5 different positions and receiving multiple certificates.",
  },
  {
    id: "exp-school-22",
    slug: "other-sports-inter-house",
    title: "Other Sports Inter-House — Cricket, Football & Gymnastics",
    year: 2021,
    dateLabel: "MYP 1 & 2",
    category: "sport",
    tier: "archive",
    themes: ["competing"],
    summary: "Represented my house in Cricket, Football and Gymnastics as an active participant in inter-house sports.",
  },
];
